# Generated by Django 4.1 on 2022-11-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riwayat', '0002_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='name',
        ),
        migrations.AddField(
            model_name='program',
            name='total_donasi',
            field=models.IntegerField(null=True),
        ),
    ]
