# Generated by Django 4.0.5 on 2022-11-01 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='deskripsi',
            field=models.CharField(max_length=10000),
        ),
    ]
