# Generated by Django 4.1 on 2022-10-31 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='deskripsi',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='karya',
            name='harga',
            field=models.BigIntegerField(),
        ),
    ]
