# Generated by Django 4.1 on 2022-11-01 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arti', '0002_alter_karya_user_alter_userarti_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='deskripsi',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='karya',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userarti',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
