# Generated by Django 4.1 on 2022-11-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileuser', '0002_alter_profile_user_alter_uploadimage_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(default='profiledefault.jpg', upload_to='images'),
        ),
    ]
